INSERT INTO cfg_import_field_mapping (data_type, target_column, source_header, required_flag, priority) VALUES
('tcp','user_account','user_account',1,10),
('tcp','user_account','account',1,20),
('tcp','user_mac','user_mac',0,10),
('tcp','user_type','user_type',1,10),
('tcp','universal_video_applications','universal_video_applications',1,10),
('tcp','universal_video_applications','application',1,20),
('tcp','statistics_duration','statistics_duration',1,10),
('tcp','statistics_duration','statistical_time',1,20),
('game','user_account','user_account',1,10),
('game','user_account','account',1,20),
('game','user_mac','user_mac',0,10),
('game','user_type','user_type',1,10),
('game','application_protocol','application_protocol',1,10),
('game','application_protocol','application',1,20),
('game','statistical_time','statistical_time',1,10),
('crm','crm_user_id','crm_user_id',1,10),
('crm','crm_user_id','customer_id',1,20),
('crm','user_account','user_account',0,10),
('crm','user_mac','user_mac',0,10),
('crm','current_plan_name','current_plan_name',0,10),
('crm','current_plan_speed_mbps','current_plan_speed_mbps',0,10),
('crm','current_arpu','current_arpu',0,10),
('crm','contract_status','contract_status',0,10),
('crm','arrears_flag','arrears_flag',0,10),
('crm','blacklist_flag','blacklist_flag',0,10),
('coverage','area_key','area_key',1,10),
('coverage','area_key','coverage_key',1,20),
('coverage','city','city',0,10),
('coverage','neighborhood','neighborhood',0,10),
('coverage','hp','hp',0,10),
('coverage','hc','hc',0,10),
('coverage','ftth_available_flag','ftth_available_flag',1,10),
('coverage','build_priority','build_priority',0,10),
('reachability','crm_user_id','crm_user_id',0,10),
('reachability','user_account','user_account',0,10),
('reachability','phone_available_flag','phone_available_flag',0,10),
('reachability','sms_available_flag','sms_available_flag',0,10),
('reachability','app_push_available_flag','app_push_available_flag',0,10),
('reachability','last_contact_result','last_contact_result',0,10)
ON DUPLICATE KEY UPDATE required_flag=VALUES(required_flag), priority=VALUES(priority), active_flag=1;

INSERT INTO cfg_final_join_rule (rule_scope, left_alias, left_column, right_alias, right_column, priority, rule_comment) VALUES
('crm','c','user_account','b','user_key',10,'CRM account to SA user key'),
('crm','c','user_mac','b','user_key',20,'CRM MAC to SA user key'),
('crm','c','crm_user_id','b','user_key',30,'CRM id to SA user key'),
('reach','r','crm_user_id','c','crm_user_id',10,'Reachability by CRM id'),
('reach','r','user_account','c','user_account',20,'Reachability by account'),
('reach','r','user_account','b','user_key',30,'Reachability direct to SA user key'),
('coverage','cv','area_key','c','crm_user_id',10,'Coverage key by CRM id'),
('coverage','cv','area_key','c','user_account',20,'Coverage key by account'),
('coverage','cv','area_key','b','user_key',30,'Coverage direct to SA user key')
ON DUPLICATE KEY UPDATE priority=VALUES(priority), rule_comment=VALUES(rule_comment), active_flag=1;
