INSERT INTO cfg_import_field_mapping (data_type, target_column, source_header, required_flag, priority) VALUES
('tcp','user_account','user_account',1,10),
('tcp','user_account','Account',1,20),
('tcp','user_account','subscriber_account',1,30),
('tcp','user_account','account_id',1,40),
('tcp','user_account','user_key',1,50),
('tcp','user_account','subscriber_id',1,60),
('tcp','user_account','Subscriber Account',1,70),
('tcp','user_account','User Account',1,80),
('tcp','user_mac','user_mac',0,10),
('tcp','user_mac','MAC',0,20),
('tcp','user_mac','device_mac',0,30),
('tcp','user_mac','User Mac',0,40),
('tcp','user_mac','User MAC',0,50),
('tcp','user_type','user_type',0,10),
('tcp','universal_video_applications','universal_video_applications',1,10),
('tcp','universal_video_applications','Application',1,20),
('tcp','universal_video_applications','app_name',1,30),
('tcp','universal_video_applications','application_name',1,40),
('tcp','universal_video_applications','universal_video_application',1,50),
('tcp','universal_video_applications','Universal Video Applications',1,60),
('tcp','universal_video_applications','Universal Video Application',1,70),
('tcp','universal_video_applications','App Name',1,80),
('tcp','statistics_duration','statistics_duration',1,10),
('tcp','statistics_duration','statistical_time',1,20),
('tcp','statistics_duration','record_time',1,30),
('tcp','statistics_duration','stat_time',1,40),
('tcp','statistics_duration','start_time',1,50),
('tcp','statistics_duration','collect_time',1,60),
('tcp','statistics_duration','Statistics Duration',1,70),
('tcp','statistics_duration','Statistical Time',1,80),
('tcp','statistics_duration','Record Time',1,90),
('tcp','statistics_duration','Start Time',1,100),
('tcp','local_ip_address','local_ip_address',0,10),
('tcp','local_ip_address','local_ip',0,20),
('tcp','local_ip_address','user_ip',0,30),
('tcp','local_ip_address','client_ip',0,40),
('tcp','vmos','vmos',0,10),
('tcp','vmos','video_mos',0,20),
('tcp','connection_establishment_success_rate','connection_establishment_success_rate',0,10),
('tcp','connection_establishment_success_rate','connection_establishment_success_rate_pct',0,20),
('tcp','connection_establishment_delay_ms','connection_establishment_delay_ms',0,10),
('tcp','connection_establishment_delay_ms','conn_delay_ms',0,20),
('tcp','upstream_data_transmission_rtt_ms','upstream_data_transmission_rtt_ms',0,10),
('tcp','upstream_data_transmission_rtt_ms','upstream_rtt_ms',0,20),
('tcp','upstream_data_transmission_rtt_ms','user_up_rtt_ms',0,30),
('tcp','downstream_data_transmission_rtt_ms','downstream_data_transmission_rtt_ms',0,10),
('tcp','downstream_data_transmission_rtt_ms','downstream_rtt_ms',0,20),
('tcp','downstream_data_transmission_rtt_ms','user_down_rtt_ms',0,30),
('tcp','network_side_rtt_ms','network_side_rtt_ms',0,10),
('tcp','network_side_rtt_ms','network_rtt_ms',0,20),
('tcp','network_side_rtt_ms','avg_network_rtt_ms',0,30),
('tcp','subscriber_side_rtt_ms','subscriber_side_rtt_ms',0,10),
('tcp','subscriber_side_rtt_ms','subscriber_rtt_ms',0,20),
('tcp','subscriber_side_rtt_ms','user_rtt_ms',0,30),
('tcp','subscriber_side_rtt_ms','avg_user_rtt_ms',0,40),
('tcp','network_side_downstream_packet_loss_rate','network_side_downstream_packet_loss_rate',0,10),
('tcp','network_side_downstream_packet_loss_rate','network_down_loss_pct',0,20),
('tcp','network_side_downstream_packet_loss_rate','network_side_downstream_packet_loss_rate_pct',0,30),
('tcp','user_side_downstream_packet_loss_rate','user_side_downstream_packet_loss_rate',0,10),
('tcp','user_side_downstream_packet_loss_rate','user_down_loss_pct',0,20),
('tcp','user_side_downstream_packet_loss_rate','user_side_downstream_packet_loss_rate_pct',0,30),
('tcp','network_side_upstream_packet_loss_rate','network_side_upstream_packet_loss_rate',0,10),
('tcp','network_side_upstream_packet_loss_rate','network_up_loss_pct',0,20),
('tcp','user_side_upstream_packet_loss_rate','user_side_upstream_packet_loss_rate',0,10),
('tcp','user_side_upstream_packet_loss_rate','user_up_loss_pct',0,20),
('tcp','server_ip','server_ip',0,10),
('tcp','throughput_avg_bandwidth_kbps','throughput_avg_bandwidth_kbps',0,10),
('tcp','throughput_avg_bandwidth_kbps','avg_bandwidth_kbps',0,20),
('tcp','user_avg_download_rate_kbps','user_avg_download_rate_kbps',0,10),
('tcp','user_avg_download_rate_kbps','user_average_download_rate_kbps',0,20),
('tcp','user_avg_effective_download_rate_kbps','user_avg_effective_download_rate_kbps',0,10),
('tcp','user_avg_effective_download_rate_kbps','user_effective_download_rate_kbps',0,20),
('tcp','download_fluency','download_fluency',0,10),
('tcp','downloaded_data_volume_kb','downloaded_data_volume_kb',1,10),
('tcp','downloaded_data_volume_kb','traffic_kb',1,20),
('tcp','downloaded_data_volume_kb','downloaded_kb',1,30),
('tcp','downloaded_data_volume_kb','data_volume_kb',1,40),
('tcp','downloaded_data_volume_kb','Downloaded Data Volume (KB)',1,50),
('tcp','downloaded_data_volume_kb','Downloaded Data Volume KB',1,60),
('tcp','downloaded_data_volume_kb','Traffic KB',1,70),
('tcp','effective_download_duration_s','effective_download_duration_s',1,10),
('tcp','effective_download_duration_s','effective_duration_s',1,20),
('tcp','effective_download_duration_s','download_effective_duration_s',1,30),
('tcp','effective_download_duration_s','Effective Download Duration (s)',1,40),
('tcp','effective_download_duration_s','Effective Download Duration',1,50),
('tcp','effective_download_duration_s','Effective Duration s',1,60),
('tcp','video_download_duration_s','video_download_duration_s',0,10),
('tcp','video_download_duration_s','video_duration_s',0,20),
('tcp','wifi_delay_ms','wifi_delay_ms',0,10),
('tcp','bras','bras',0,10),
('tcp','olt','olt',0,10),
('tcp','pon','pon',0,10),
('tcp','wan_type','wan_type',0,10),
('tcp','wan_type','access_type',0,20),
('tcp','device_characteristic','device_characteristic',0,10),
('tcp','device_description','device_description',0,10),
('game','user_account','user_account',1,10),
('game','user_account','account',1,20),
('game','user_mac','user_mac',0,10),
('game','user_type','user_type',0,10),
('game','application_protocol','application_protocol',1,10),
('game','application_protocol','application',1,20),
('game','statistical_time','statistical_time',1,10),
('crm','crm_user_id','crm_user_id',1,10),
('crm','crm_user_id','customer_id',1,20),
('crm','user_account','user_account',0,10),
('crm','user_mac','user_mac',0,10),
('crm','current_plan_name','current_plan_name',0,10),
('crm','current_plan_speed_mbps','current_plan_speed_mbps',0,10),
('crm','current_arpu','current_arpu',0,10),
('crm','contract_status','contract_status',0,10),
('crm','arrears_flag','arrears_flag',0,10),
('crm','blacklist_flag','blacklist_flag',0,10),
('coverage','area_key','area_key',1,10),
('coverage','area_key','coverage_key',1,20),
('coverage','city','city',0,10),
('coverage','neighborhood','neighborhood',0,10),
('coverage','hp','hp',0,10),
('coverage','hc','hc',0,10),
('coverage','ftth_available_flag','ftth_available_flag',1,10),
('coverage','build_priority','build_priority',0,10),
('reachability','crm_user_id','crm_user_id',0,10),
('reachability','user_account','user_account',0,10),
('reachability','phone_available_flag','phone_available_flag',0,10),
('reachability','sms_available_flag','sms_available_flag',0,10),
('reachability','app_push_available_flag','app_push_available_flag',0,10),
('reachability','last_contact_result','last_contact_result',0,10)
ON DUPLICATE KEY UPDATE required_flag=VALUES(required_flag), priority=VALUES(priority), active_flag=1;

INSERT INTO cfg_final_join_rule (rule_scope, left_alias, left_column, right_alias, right_column, priority, rule_comment) VALUES
('crm','c','user_account','b','user_key',10,'CRM account to SA user key'),
('crm','c','user_mac','b','user_key',20,'CRM MAC to SA user key'),
('crm','c','crm_user_id','b','user_key',30,'CRM id to SA user key'),
('reach','r','crm_user_id','c','crm_user_id',10,'Reachability by CRM id'),
('reach','r','user_account','c','user_account',20,'Reachability by account'),
('reach','r','user_account','b','user_key',30,'Reachability direct to SA user key'),
('coverage','cv','area_key','c','crm_user_id',10,'Coverage key by CRM id'),
('coverage','cv','area_key','c','user_account',20,'Coverage key by account'),
('coverage','cv','area_key','b','user_key',30,'Coverage direct to SA user key')
ON DUPLICATE KEY UPDATE priority=VALUES(priority), rule_comment=VALUES(rule_comment), active_flag=1;
