-- Deprecated compatibility marker.
-- Quality Gate is now routed by batch data_type:
-- - 001_tcp_raw_quality_gate.sql
-- - 002_game_raw_quality_gate.sql
--
-- Do not execute this file directly. The routed templates normalize stat_time_text
-- before guarded STR_TO_DATE parsing and avoid scanning non-applicable RAW tables.
