-- Analytics cockpit dedicated ADS schema.
-- Keep dashboard queries on ADS/DWS instead of RAW.

CREATE TABLE IF NOT EXISTS ads_dashboard_kpi_summary (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  kpi_group VARCHAR(64) NOT NULL DEFAULT 'overview',
  kpi_key VARCHAR(128) NOT NULL,
  kpi_label VARCHAR(255) NOT NULL,
  kpi_value DECIMAL(24,6) NULL,
  kpi_unit VARCHAR(32) NULL,
  kpi_hint VARCHAR(512) NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, kpi_key),
  INDEX ix_batch_group (import_batch_id, kpi_group, display_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads_app_experience_rank (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  app_category VARCHAR(64) NOT NULL,
  app_name VARCHAR(255) NOT NULL,
  user_type VARCHAR(32) NOT NULL DEFAULT 'ALL',
  active_users BIGINT NOT NULL DEFAULT 0,
  traffic_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  duration_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  avg_effective_mbps DECIMAL(18,6) NULL,
  avg_vmos DECIMAL(18,6) NULL,
  avg_mos DECIMAL(18,6) NULL,
  avg_subscriber_rtt_ms DECIMAL(18,6) NULL,
  avg_network_rtt_ms DECIMAL(18,6) NULL,
  avg_user_loss_pct DECIMAL(18,6) NULL,
  avg_network_loss_pct DECIMAL(18,6) NULL,
  poor_experience_users BIGINT NOT NULL DEFAULT 0,
  poor_experience_user_pct DECIMAL(18,6) NULL,
  main_issue_driver VARCHAR(128) NULL,
  evidence_summary TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, app_category, app_name, user_type),
  INDEX ix_app_rank (analysis_run_id, traffic_gb, active_users),
  INDEX ix_batch_app (import_batch_id, app_category, user_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads_hourly_experience_trend (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  stat_date DATE NOT NULL,
  hour_of_day TINYINT NOT NULL,
  user_type VARCHAR(32) NOT NULL DEFAULT 'ALL',
  app_category VARCHAR(64) NOT NULL DEFAULT 'ALL',
  active_users BIGINT NOT NULL DEFAULT 0,
  traffic_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  duration_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  avg_effective_mbps DECIMAL(18,6) NULL,
  avg_vmos DECIMAL(18,6) NULL,
  avg_mos DECIMAL(18,6) NULL,
  avg_subscriber_rtt_ms DECIMAL(18,6) NULL,
  avg_network_rtt_ms DECIMAL(18,6) NULL,
  avg_user_loss_pct DECIMAL(18,6) NULL,
  avg_network_loss_pct DECIMAL(18,6) NULL,
  poor_experience_users BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, stat_date, hour_of_day, user_type, app_category),
  INDEX ix_hourly_batch (import_batch_id, hour_of_day, user_type),
  INDEX ix_hourly_run (analysis_run_id, hour_of_day, app_category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads_network_hotspot_rank (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  bras VARCHAR(255) NOT NULL DEFAULT 'UNKNOWN',
  olt VARCHAR(255) NOT NULL DEFAULT 'UNKNOWN',
  pon VARCHAR(255) NOT NULL DEFAULT 'UNKNOWN',
  user_type VARCHAR(32) NOT NULL DEFAULT 'ALL',
  affected_users BIGINT NOT NULL DEFAULT 0,
  traffic_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  avg_subscriber_rtt_ms DECIMAL(18,6) NULL,
  avg_network_rtt_ms DECIMAL(18,6) NULL,
  avg_user_loss_pct DECIMAL(18,6) NULL,
  avg_network_loss_pct DECIMAL(18,6) NULL,
  avg_wifi_delay_ms DECIMAL(18,6) NULL,
  poor_experience_user_pct DECIMAL(18,6) NULL,
  main_issue_driver VARCHAR(128) NULL,
  suggested_action VARCHAR(255) NULL,
  evidence_summary TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, bras, olt, pon, user_type),
  INDEX ix_hotspot_rank (analysis_run_id, affected_users, poor_experience_user_pct),
  INDEX ix_hotspot_batch (import_batch_id, bras, olt, pon)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads_user_experience_profile (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  user_key VARCHAR(255) NOT NULL,
  user_type VARCHAR(32) NULL,
  active_days BIGINT NOT NULL DEFAULT 0,
  active_hours BIGINT NOT NULL DEFAULT 0,
  total_traffic_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  video_traffic_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  game_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  top_app_category VARCHAR(64) NULL,
  avg_effective_mbps DECIMAL(18,6) NULL,
  avg_vmos DECIMAL(18,6) NULL,
  avg_mos DECIMAL(18,6) NULL,
  avg_subscriber_rtt_ms DECIMAL(18,6) NULL,
  avg_network_rtt_ms DECIMAL(18,6) NULL,
  avg_user_loss_pct DECIMAL(18,6) NULL,
  avg_network_loss_pct DECIMAL(18,6) NULL,
  bottleneck_side VARCHAR(64) NULL,
  issue_driver VARCHAR(128) NULL,
  lead_type VARCHAR(128) NULL,
  demand_score INT NULL,
  migration_motive_score INT NULL,
  recommended_offer VARCHAR(512) NULL,
  evidence_summary TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, user_key),
  INDEX ix_user_profile_rank (analysis_run_id, total_traffic_gb, game_hours),
  INDEX ix_user_profile_batch (import_batch_id, user_type, lead_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads_lead_evidence_detail (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  user_key VARCHAR(255) NOT NULL,
  user_type VARCHAR(32) NULL,
  lead_type VARCHAR(128) NOT NULL,
  demand_score INT NOT NULL DEFAULT 0,
  migration_motive_score INT NOT NULL DEFAULT 0,
  recommended_offer VARCHAR(512) NULL,
  top_app_category VARCHAR(64) NULL,
  total_traffic_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  video_traffic_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  game_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  avg_effective_mbps DECIMAL(18,6) NULL,
  avg_vmos DECIMAL(18,6) NULL,
  avg_mos DECIMAL(18,6) NULL,
  bottleneck_side VARCHAR(64) NULL,
  issue_driver VARCHAR(128) NULL,
  final_action VARCHAR(512) NULL,
  ftth_available_flag VARCHAR(32) NULL,
  reachable_flag VARCHAR(32) NULL,
  evidence_summary TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, user_key),
  INDEX ix_lead_type_rank (analysis_run_id, lead_type, demand_score, migration_motive_score),
  INDEX ix_lead_action (analysis_run_id, final_action(64))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
