-- Versioned experience-analysis policy and V2 metric foundation.
-- MySQL 8.0. This migration is additive and preserves all 1.0.x result tables.

-- `default_access_type` is the explicit Others mapping. The Rust migration
-- loader changes existing installations to nullable only when needed; keeping
-- that conditional ALTER out of this repeatable SQL avoids a metadata rewrite
-- every time the import environment is prepared.

CREATE TABLE IF NOT EXISTS meta_experience_analysis_policy (
  policy_id VARCHAR(64) NOT NULL PRIMARY KEY,
  version BIGINT NOT NULL,
  policy_name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  persistent_min_valid_obs BIGINT NOT NULL,
  persistent_min_poor_obs BIGINT NOT NULL,
  persistent_min_poor_rate_pct DECIMAL(9,4) NOT NULL,
  severe_user_min_valid_obs BIGINT NOT NULL,
  severe_user_min_severe_obs BIGINT NOT NULL,
  severe_user_min_severe_rate_pct DECIMAL(9,4) NOT NULL,
  minimum_app_eligible_users BIGINT NOT NULL,
  minimum_app_valid_obs BIGINT NOT NULL,
  finding_attention_persistent_user_rate_pct DECIMAL(9,4) NOT NULL,
  finding_severe_user_rate_pct DECIMAL(9,4) NOT NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  published_at DATETIME NULL,
  UNIQUE KEY uk_experience_policy_version (version),
  INDEX ix_experience_policy_status (status, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dim_app_experience_profile (
  profile_id VARCHAR(64) NOT NULL PRIMARY KEY,
  policy_id VARCHAR(64) NOT NULL,
  profile_code VARCHAR(64) NOT NULL,
  profile_name VARCHAR(255) NOT NULL,
  data_type VARCHAR(32) NOT NULL,
  app_category VARCHAR(64) NULL,
  priority INT NOT NULL DEFAULT 100,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  poor_vmos_below DECIMAL(18,6) NULL,
  poor_mos_below DECIMAL(18,6) NULL,
  poor_subscriber_rtt_ms_at_least DECIMAL(18,6) NULL,
  poor_network_rtt_ms_at_least DECIMAL(18,6) NULL,
  poor_user_loss_pct_at_least DECIMAL(18,6) NULL,
  poor_network_loss_pct_at_least DECIMAL(18,6) NULL,
  poor_jitter_ms_at_least DECIMAL(18,6) NULL,
  severe_vmos_below DECIMAL(18,6) NULL,
  severe_mos_below DECIMAL(18,6) NULL,
  severe_subscriber_rtt_ms_at_least DECIMAL(18,6) NULL,
  severe_network_rtt_ms_at_least DECIMAL(18,6) NULL,
  severe_user_loss_pct_at_least DECIMAL(18,6) NULL,
  severe_network_loss_pct_at_least DECIMAL(18,6) NULL,
  severe_jitter_ms_at_least DECIMAL(18,6) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_policy_profile_code (policy_id, profile_code),
  INDEX ix_profile_match (policy_id, data_type, app_category, enabled, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS meta_analysis_run_policy_binding (
  analysis_run_id VARCHAR(64) NOT NULL PRIMARY KEY,
  import_batch_id VARCHAR(64) NOT NULL,
  access_rule_set_id VARCHAR(64) NULL,
  access_rule_set_version BIGINT NULL,
  others_access_type VARCHAR(32) NULL,
  app_mapping_version BIGINT NULL,
  experience_policy_id VARCHAR(64) NOT NULL,
  experience_policy_version BIGINT NOT NULL,
  policy_snapshot JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX ix_policy_binding_batch (import_batch_id, analysis_run_id),
  INDEX ix_policy_binding_version (experience_policy_id, experience_policy_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dws_user_app_period_experience_v2 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  grain_hash BINARY(16) NOT NULL,
  user_key VARCHAR(255) NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  app_category VARCHAR(64) NOT NULL,
  app_name VARCHAR(255) NOT NULL,
  data_type VARCHAR(32) NOT NULL,
  profile_code VARCHAR(64) NOT NULL,
  policy_version BIGINT NOT NULL,
  observation_rows BIGINT NOT NULL DEFAULT 0,
  valid_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_obs_rows BIGINT NOT NULL DEFAULT 0,
  severe_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_observation_rate_pct DECIMAL(18,6) NULL,
  severe_observation_rate_pct DECIMAL(18,6) NULL,
  eligible_user_flag TINYINT(1) NOT NULL DEFAULT 0,
  ever_affected_user_flag TINYINT(1) NOT NULL DEFAULT 0,
  persistent_poor_user_flag TINYINT(1) NOT NULL DEFAULT 0,
  severe_poor_user_flag TINYINT(1) NOT NULL DEFAULT 0,
  poor_vmos_obs BIGINT NOT NULL DEFAULT 0,
  poor_mos_obs BIGINT NOT NULL DEFAULT 0,
  poor_subscriber_rtt_obs BIGINT NOT NULL DEFAULT 0,
  poor_network_rtt_obs BIGINT NOT NULL DEFAULT 0,
  poor_user_loss_obs BIGINT NOT NULL DEFAULT 0,
  poor_network_loss_obs BIGINT NOT NULL DEFAULT 0,
  poor_jitter_obs BIGINT NOT NULL DEFAULT 0,
  total_download_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  total_game_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  avg_effective_download_mbps DECIMAL(18,6) NULL,
  avg_vmos DECIMAL(18,6) NULL,
  avg_mos DECIMAL(18,6) NULL,
  avg_subscriber_rtt_ms DECIMAL(18,6) NULL,
  avg_network_rtt_ms DECIMAL(18,6) NULL,
  avg_user_loss_pct DECIMAL(18,6) NULL,
  avg_network_loss_pct DECIMAL(18,6) NULL,
  avg_jitter_ms DECIMAL(18,6) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_app_period_v2 (analysis_run_id, grain_hash),
  INDEX ix_user_app_period_app (analysis_run_id, app_name(128), user_type),
  INDEX ix_user_app_period_flags (analysis_run_id, persistent_poor_user_flag, severe_poor_user_flag),
  INDEX ix_user_app_period_user (import_batch_id, user_key(128))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dws_app_access_period_experience_v2 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  grain_hash BINARY(16) NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  app_category VARCHAR(64) NOT NULL,
  app_name VARCHAR(255) NOT NULL,
  data_type VARCHAR(32) NOT NULL,
  profile_code VARCHAR(64) NOT NULL,
  policy_version BIGINT NOT NULL,
  observed_users BIGINT NOT NULL DEFAULT 0,
  eligible_users BIGINT NOT NULL DEFAULT 0,
  observation_rows BIGINT NOT NULL DEFAULT 0,
  valid_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_obs_rows BIGINT NOT NULL DEFAULT 0,
  severe_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_observation_rate_pct DECIMAL(18,6) NULL,
  ever_affected_users BIGINT NOT NULL DEFAULT 0,
  ever_affected_user_rate_pct DECIMAL(18,6) NULL,
  persistent_poor_users BIGINT NOT NULL DEFAULT 0,
  persistent_poor_user_rate_pct DECIMAL(18,6) NULL,
  severe_poor_users BIGINT NOT NULL DEFAULT 0,
  severe_poor_user_rate_pct DECIMAL(18,6) NULL,
  sample_status VARCHAR(32) NOT NULL,
  main_issue_driver VARCHAR(64) NULL,
  total_download_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  total_game_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  avg_effective_download_mbps DECIMAL(18,6) NULL,
  avg_vmos DECIMAL(18,6) NULL,
  avg_mos DECIMAL(18,6) NULL,
  avg_subscriber_rtt_ms DECIMAL(18,6) NULL,
  avg_network_rtt_ms DECIMAL(18,6) NULL,
  avg_user_loss_pct DECIMAL(18,6) NULL,
  avg_network_loss_pct DECIMAL(18,6) NULL,
  avg_jitter_ms DECIMAL(18,6) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_app_access_period_v2 (analysis_run_id, grain_hash),
  INDEX ix_app_access_period_rank (analysis_run_id, sample_status, persistent_poor_user_rate_pct, eligible_users),
  INDEX ix_app_access_period_app (import_batch_id, app_name(128), user_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dws_user_app_hourly_experience_v2 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  grain_hash BINARY(16) NOT NULL,
  stat_date DATE NOT NULL,
  hour_of_day TINYINT NOT NULL,
  user_key VARCHAR(255) NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  app_category VARCHAR(64) NOT NULL,
  app_name VARCHAR(255) NOT NULL,
  data_type VARCHAR(32) NOT NULL,
  profile_code VARCHAR(64) NOT NULL,
  policy_version BIGINT NOT NULL,
  valid_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_obs_rows BIGINT NOT NULL DEFAULT 0,
  severe_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_observation_rate_pct DECIMAL(18,6) NULL,
  persistent_poor_user_flag TINYINT(1) NOT NULL DEFAULT 0,
  severe_poor_user_flag TINYINT(1) NOT NULL DEFAULT 0,
  avg_vmos DECIMAL(18,6) NULL,
  avg_mos DECIMAL(18,6) NULL,
  avg_subscriber_rtt_ms DECIMAL(18,6) NULL,
  avg_network_rtt_ms DECIMAL(18,6) NULL,
  avg_user_loss_pct DECIMAL(18,6) NULL,
  avg_network_loss_pct DECIMAL(18,6) NULL,
  avg_jitter_ms DECIMAL(18,6) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_app_hourly_v2 (analysis_run_id, grain_hash),
  INDEX ix_user_app_hourly_scope (analysis_run_id, app_name(96), user_type, stat_date, hour_of_day),
  INDEX ix_user_app_hourly_flags (analysis_run_id, persistent_poor_user_flag, severe_poor_user_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads_app_hourly_experience_v2 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  grain_hash BINARY(16) NOT NULL,
  stat_date DATE NOT NULL,
  hour_of_day TINYINT NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  app_category VARCHAR(64) NOT NULL,
  app_name VARCHAR(255) NOT NULL,
  eligible_users BIGINT NOT NULL DEFAULT 0,
  valid_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_observation_rate_pct DECIMAL(18,6) NULL,
  persistent_poor_users BIGINT NOT NULL DEFAULT 0,
  severe_poor_users BIGINT NOT NULL DEFAULT 0,
  sample_status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ads_app_hourly_v2 (analysis_run_id, grain_hash),
  INDEX ix_ads_app_hourly_scope (analysis_run_id, app_name(96), user_type, stat_date, hour_of_day),
  INDEX ix_ads_app_hourly_rank (analysis_run_id, sample_status, poor_observation_rate_pct, eligible_users)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads_app_experience_v2 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  grain_hash BINARY(16) NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  app_category VARCHAR(64) NOT NULL,
  app_name VARCHAR(255) NOT NULL,
  data_type VARCHAR(32) NOT NULL,
  profile_code VARCHAR(64) NOT NULL,
  policy_version BIGINT NOT NULL,
  observed_users BIGINT NOT NULL DEFAULT 0,
  eligible_users BIGINT NOT NULL DEFAULT 0,
  valid_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_observation_rate_pct DECIMAL(18,6) NULL,
  ever_affected_users BIGINT NOT NULL DEFAULT 0,
  ever_affected_user_rate_pct DECIMAL(18,6) NULL,
  persistent_poor_users BIGINT NOT NULL DEFAULT 0,
  persistent_poor_user_rate_pct DECIMAL(18,6) NULL,
  severe_poor_users BIGINT NOT NULL DEFAULT 0,
  severe_poor_user_rate_pct DECIMAL(18,6) NULL,
  sample_status VARCHAR(32) NOT NULL,
  attention_level VARCHAR(32) NOT NULL,
  main_issue_driver VARCHAR(64) NULL,
  data_limitation_code VARCHAR(64) NULL,
  evidence_summary TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ads_app_experience_v2 (analysis_run_id, grain_hash),
  INDEX ix_ads_app_v2_rank (analysis_run_id, attention_level, persistent_poor_user_rate_pct, eligible_users),
  INDEX ix_ads_app_v2_filter (import_batch_id, user_type, app_name(128))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Provisional V1 defaults reproduce the old observation-level poor thresholds,
-- while adding explicit sample, persistence and severe-user rules. They are
-- configuration rows, not SQL constants in the aggregation queries.
INSERT IGNORE INTO meta_experience_analysis_policy (
  policy_id, version, policy_name, status,
  persistent_min_valid_obs, persistent_min_poor_obs, persistent_min_poor_rate_pct,
  severe_user_min_valid_obs, severe_user_min_severe_obs, severe_user_min_severe_rate_pct,
  minimum_app_eligible_users, minimum_app_valid_obs,
  finding_attention_persistent_user_rate_pct, finding_severe_user_rate_pct,
  notes, published_at
) VALUES (
  'POLICY_BASELINE_V1', 1, 'Baseline experience policy V1', 'published',
  5, 2, 20.0000,
  5, 2, 10.0000,
  30, 100,
  10.0000, 5.0000,
  'Provisional defaults; review against representative TCP and Game distributions before production use.',
  CURRENT_TIMESTAMP
);

INSERT IGNORE INTO dim_app_experience_profile (
  profile_id, policy_id, profile_code, profile_name, data_type, app_category, priority,
  poor_vmos_below, poor_mos_below, poor_subscriber_rtt_ms_at_least,
  poor_network_rtt_ms_at_least, poor_user_loss_pct_at_least,
  poor_network_loss_pct_at_least, poor_jitter_ms_at_least,
  severe_vmos_below, severe_mos_below, severe_subscriber_rtt_ms_at_least,
  severe_network_rtt_ms_at_least, severe_user_loss_pct_at_least,
  severe_network_loss_pct_at_least, severe_jitter_ms_at_least
) VALUES
  (
    'PROFILE_BASELINE_TCP', 'POLICY_BASELINE_V1', 'GENERIC_TCP', 'Generic TCP experience', 'tcp', NULL, 1000,
    3.5, NULL, 50, 100, 1, 2, NULL,
    2.5, NULL, 150, 250, 5, 5, NULL
  ),
  (
    'PROFILE_BASELINE_GAME', 'POLICY_BASELINE_V1', 'GENERIC_GAME', 'Generic Game experience', 'game', NULL, 1000,
    NULL, 3.5, 100, NULL, 1, NULL, 50,
    NULL, 2.5, 200, NULL, 5, NULL, 100
  );
