-- Opportunity workbench V4: reusable user features, resumable candidate staging and atomic publish.

CREATE TABLE IF NOT EXISTS dws_user_opportunity_feature_v2 (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  user_key VARCHAR(255) NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  active_days BIGINT NOT NULL DEFAULT 0,
  observation_rows BIGINT NOT NULL DEFAULT 0,
  total_download_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  total_effective_duration_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  avg_effective_download_mbps DECIMAL(18,6) NULL,
  avg_wifi_delay_ms DECIMAL(18,6) NULL,
  avg_subscriber_rtt_ms DECIMAL(18,6) NULL,
  avg_network_rtt_ms DECIMAL(18,6) NULL,
  avg_user_loss_pct DECIMAL(18,6) NULL,
  avg_network_loss_pct DECIMAL(18,6) NULL,
  primary_app VARCHAR(255) NULL,
  primary_app_active_days BIGINT NOT NULL DEFAULT 0,
  primary_app_observations BIGINT NOT NULL DEFAULT 0,
  rule_profile_version BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, user_key),
  INDEX ix_opportunity_feature_batch (import_batch_id, analysis_run_id),
  INDEX ix_opportunity_feature_access (analysis_run_id, user_type, active_days)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stg_opportunity_user_v3 (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  user_key VARCHAR(255) NOT NULL,
  opportunity_type VARCHAR(64) NOT NULL,
  opportunity_level VARCHAR(32) NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  active_days BIGINT NOT NULL DEFAULT 0,
  observation_rows BIGINT NOT NULL DEFAULT 0,
  total_download_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  total_effective_duration_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  avg_effective_download_mbps DECIMAL(18,6) NULL,
  avg_wifi_delay_ms DECIMAL(18,6) NULL,
  avg_subscriber_rtt_ms DECIMAL(18,6) NULL,
  avg_network_rtt_ms DECIMAL(18,6) NULL,
  avg_user_loss_pct DECIMAL(18,6) NULL,
  avg_network_loss_pct DECIMAL(18,6) NULL,
  primary_app VARCHAR(255) NULL,
  primary_app_active_days BIGINT NOT NULL DEFAULT 0,
  primary_app_observations BIGINT NOT NULL DEFAULT 0,
  evidence_value DECIMAL(24,6) NULL,
  evidence_unit VARCHAR(32) NULL,
  evidence_summary TEXT NOT NULL,
  data_limitation_code VARCHAR(64) NULL,
  rule_profile_version BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, user_key, opportunity_type),
  INDEX ix_opportunity_staging_type (analysis_run_id, opportunity_type, opportunity_level),
  INDEX ix_opportunity_staging_batch (import_batch_id, analysis_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dws_user_access_period_v2 (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  user_key VARCHAR(255) NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  observation_rows BIGINT NOT NULL DEFAULT 0,
  valid_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_obs_rows BIGINT NOT NULL DEFAULT 0,
  severe_obs_rows BIGINT NOT NULL DEFAULT 0,
  persistent_poor_user_flag TINYINT NOT NULL DEFAULT 0,
  severe_poor_user_flag TINYINT NOT NULL DEFAULT 0,
  total_download_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  total_effective_duration_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  active_days BIGINT NOT NULL DEFAULT 0,
  effective_download_mbps_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  effective_download_mbps_count BIGINT NOT NULL DEFAULT 0,
  subscriber_rtt_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  subscriber_rtt_count BIGINT NOT NULL DEFAULT 0,
  network_rtt_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  network_rtt_count BIGINT NOT NULL DEFAULT 0,
  user_loss_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  user_loss_count BIGINT NOT NULL DEFAULT 0,
  network_loss_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  network_loss_count BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, user_key, user_type),
  INDEX ix_user_access_batch (import_batch_id, analysis_run_id, user_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads_access_overview_v2 (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  observed_users BIGINT NOT NULL DEFAULT 0,
  eligible_users BIGINT NOT NULL DEFAULT 0,
  observation_rows BIGINT NOT NULL DEFAULT 0,
  valid_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_obs_rows BIGINT NOT NULL DEFAULT 0,
  persistent_poor_users BIGINT NOT NULL DEFAULT 0,
  severe_poor_users BIGINT NOT NULL DEFAULT 0,
  total_download_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  total_effective_duration_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  avg_effective_download_mbps DECIMAL(18,6) NULL,
  avg_subscriber_rtt_ms DECIMAL(18,6) NULL,
  avg_network_rtt_ms DECIMAL(18,6) NULL,
  avg_user_loss_pct DECIMAL(18,6) NULL,
  avg_network_loss_pct DECIMAL(18,6) NULL,
  effective_download_mbps_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  effective_download_mbps_count BIGINT NOT NULL DEFAULT 0,
  subscriber_rtt_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  subscriber_rtt_count BIGINT NOT NULL DEFAULT 0,
  network_rtt_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  network_rtt_count BIGINT NOT NULL DEFAULT 0,
  user_loss_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  user_loss_count BIGINT NOT NULL DEFAULT 0,
  network_loss_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  network_loss_count BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, user_type),
  INDEX ix_access_overview_batch (import_batch_id, analysis_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads_access_hourly_v2 (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  hour_of_day TINYINT NOT NULL,
  observed_users BIGINT NOT NULL DEFAULT 0,
  observation_rows BIGINT NOT NULL DEFAULT 0,
  valid_obs_rows BIGINT NOT NULL DEFAULT 0,
  poor_obs_rows BIGINT NOT NULL DEFAULT 0,
  total_download_gb DECIMAL(24,6) NOT NULL DEFAULT 0,
  total_effective_duration_hours DECIMAL(24,6) NOT NULL DEFAULT 0,
  avg_effective_download_mbps DECIMAL(18,6) NULL,
  avg_subscriber_rtt_ms DECIMAL(18,6) NULL,
  avg_network_rtt_ms DECIMAL(18,6) NULL,
  avg_user_loss_pct DECIMAL(18,6) NULL,
  avg_network_loss_pct DECIMAL(18,6) NULL,
  effective_download_mbps_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  effective_download_mbps_count BIGINT NOT NULL DEFAULT 0,
  subscriber_rtt_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  subscriber_rtt_count BIGINT NOT NULL DEFAULT 0,
  network_rtt_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  network_rtt_count BIGINT NOT NULL DEFAULT 0,
  user_loss_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  user_loss_count BIGINT NOT NULL DEFAULT 0,
  network_loss_sum DECIMAL(30,6) NOT NULL DEFAULT 0,
  network_loss_count BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, user_type, hour_of_day),
  INDEX ix_access_hourly_batch (import_batch_id, analysis_run_id, hour_of_day)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads_access_user_band_v2 (
  analysis_run_id VARCHAR(64) NOT NULL,
  import_batch_id VARCHAR(64) NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  dimension_code VARCHAR(64) NOT NULL,
  band_code VARCHAR(64) NOT NULL,
  band_label VARCHAR(128) NOT NULL,
  band_order INT NOT NULL,
  users BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (analysis_run_id, user_type, dimension_code, band_code),
  INDEX ix_access_band_batch (import_batch_id, analysis_run_id, dimension_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
